// src/main/java/tterrag1112/life_in_the_village/Village/Decoration/Roads/TrunkGraph.java
package tterrag1112.life_in_the_village.Village.Decoration.Roads;

import net.minecraft.core.BlockPos;

import java.util.*;

/**
 * Trunk-and-spur road graph for a village. Generated by
 * {@link TrunkRoadPlanner} before buildings are placed; consumed by
 * {@code VillagePlanner} (for cluster anchor snapping) and
 * {@code VillageRoadNetwork} (for rendering).
 *
 * <h3>Two-level structure</h3>
 * <ul>
 *   <li><b>Nodes</b> — points where trunks meet, end, or where buildings
 *       can attach. Each node has a position and a tier (the road tier
 *       at that node).</li>
 *   <li><b>Edges</b> — connections between two nodes. The edge tier is
 *       the higher of the two endpoint tiers. Edges carry centerline
 *       points so the renderer can place road blocks along them.</li>
 * </ul>
 *
 * <h3>What this graph is NOT</h3>
 * It does not store placed blocks — that's {@code VillageRoadNetwork}'s
 * job. It does not know about specific buildings — building→trunk
 * snapping is done by the planner reading this graph. It does not
 * persist — it's regenerated each time the village is planned.
 */
public class TrunkGraph {

    public static class Node {
        public final int id;
        public final BlockPos pos;
        public final RoadShape.RoadTier tier;
        public final List<Edge> edges = new ArrayList<>();

        Node(int id, BlockPos pos, RoadShape.RoadTier tier) {
            this.id = id;
            this.pos = pos;
            this.tier = tier;
        }
    }

    public static class Edge {
        public final Node a;
        public final Node b;
        public final RoadShape.RoadTier tier;
        public final List<BlockPos> centerline;

        Edge(Node a, Node b, RoadShape.RoadTier tier, List<BlockPos> centerline) {
            this.a = a;
            this.b = b;
            this.tier = tier;
            this.centerline = centerline;
        }
    }

    private final List<Node> nodes = new ArrayList<>();
    private final List<Edge> edges = new ArrayList<>();
    private int nextId = 0;

    public List<Node> getNodes() { return Collections.unmodifiableList(nodes); }
    public List<Edge> getEdges() { return Collections.unmodifiableList(edges); }

    public Node addNode(BlockPos pos, RoadShape.RoadTier tier) {
        Node n = new Node(nextId++, pos, tier);
        nodes.add(n);
        return n;
    }

    public Edge connect(Node a, Node b, RoadShape.RoadTier tier, List<BlockPos> centerline) {
        Edge e = new Edge(a, b, tier, centerline);
        edges.add(e);
        a.edges.add(e);
        b.edges.add(e);
        return e;
    }

    /**
     * Returns the node closest to a given world position. Used by the
     * planner to snap building cluster anchors onto the trunk network.
     */
    public Node nearestNode(BlockPos pos) {
        Node best = null;
        double bestDistSq = Double.MAX_VALUE;
        for (Node n : nodes) {
            double d = n.pos.distSqr(pos);
            if (d < bestDistSq) { bestDistSq = d; best = n; }
        }
        return best;
    }

    /**
     * Returns the position on any edge centerline closest to the given
     * world position. Used when buildings should snap to a road segment
     * rather than to a node — gives more flexibility for cluster member
     * placement along long trunk segments.
     */
    public BlockPos nearestPointOnAnyEdge(BlockPos pos) {
        BlockPos best = null;
        double bestDistSq = Double.MAX_VALUE;
        for (Edge e : edges) {
            for (BlockPos p : e.centerline) {
                double d = p.distSqr(pos);
                if (d < bestDistSq) { bestDistSq = d; best = p; }
            }
        }
        return best;
    }

    public boolean isEmpty() { return nodes.isEmpty(); }
}