package tterrag1112.life_in_the_village.Kingdom.Castle;


import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.resources.Identifier;
import net.minecraft.util.valueproviders.IntProvider;
import net.minecraft.util.valueproviders.UniformInt;

/**
 * Central configuration record for castle generation.
 * All three generation layers consume this record.
 * Intended to be loaded from JSON via NeoForge's data-driven system,
 * making new styles addable by datapacks without code changes.
 *
 * Example JSON location: data/yourmod/castle_styles/norman.json
 */
public record CastleStyle(

        // --- Layout ---
        PlanType planType,
        int minRadius,          // inner radius of castle footprint in blocks
        int maxRadius,

        // --- Walls ---
        int minWallHeight,
        int maxWallHeight,
        int wallThickness,      // typically 2–4

        // --- Towers ---
        TowerShape towerShape,
        int minTowerRadius,     // for round towers: block radius; for square: half-width
        int maxTowerRadius,
        int towerHeightBonus,   // how many blocks taller than adjacent wall
        float towerFrequency,   // 0–1: probability of tower at each eligible wall corner

        // --- Keep / donjon ---
        boolean hasDonjon,
        int donjeonMinSize,     // half-width of square donjon footprint
        int donjeonMaxSize,
        int donjeonHeightBonus, // extra height above tallest tower

        // --- Inner ward ---
        boolean hasInnerWard,
        float innerWardScale,   // inner wall radius as fraction of outer (e.g. 0.5)

        // --- Features ---
        boolean hasMoat,
        int moatWidth,
        int moatDepth,
        boolean hasPortcullis,
        boolean hasDrawbridge,

        // --- Materials ---
        MaterialPalette primaryMaterial,
        MaterialPalette accentMaterial,
        MaterialPalette floorMaterial,

        // --- Structure file pools (ResourceLocation keys into structure pool) ---
        Identifier battlementPool,    // pool of battlement cap templates
        Identifier gatehousePool,     // pool of gatehouse templates
        Identifier windowPool,        // pool of window/arrow-slit templates
        Identifier towerRoofPool,     // pool of tower roof/cap templates
        Identifier donjeonRoofPool,   // pool of keep roof templates
        Identifier interiorPool,      // pool of interior detail templates (optional)

        // --- Ruination ---
        float ruinationLevel,   // 0.0 = pristine, 1.0 = collapsed ruin

        // --- Misc ---
        boolean addTorches,
        boolean addFlags,
        long styleSeed         // extra seed mixed in so two NORMAN castles still differ

) {

    // -------------------------------------------------------------------------
    // Enums
    // -------------------------------------------------------------------------

    public enum PlanType {
        /** Simple 4-corner square curtain wall. */
        SQUARE,
        /** Rectangular, longer on one axis. */
        RECTANGLE,
        /** Regular polygon (5–8 sides). Side count chosen from style config. */
        POLYGON,
        /** Two concentric curtain walls. */
        CONCENTRIC,
        /** Irregular polygon generated by perturbing a base polygon. */
        IRREGULAR
    }

    public enum TowerShape {
        ROUND,
        SQUARE,
        /** Half-round tower projecting from a flat wall face. */
        D_SHAPED,
        POLYGONAL   // hexagonal or octagonal cross-section
    }

    // -------------------------------------------------------------------------
    // Codec — enables loading from JSON via NeoForge DatapackBuiltinEntriesProvider
    // -------------------------------------------------------------------------

    public static final Codec<CastleStyle> CODEC = RecordCodecBuilder.create(instance ->
            instance.group(
                    PlanType.CODEC.fieldOf("plan_type").forGetter(CastleStyle::planType),
                    Codec.INT.fieldOf("min_radius").forGetter(CastleStyle::minRadius),
                    Codec.INT.fieldOf("max_radius").forGetter(CastleStyle::maxRadius),
                    Codec.INT.fieldOf("min_wall_height").forGetter(CastleStyle::minWallHeight),
                    Codec.INT.fieldOf("max_wall_height").forGetter(CastleStyle::maxWallHeight),
                    Codec.INT.fieldOf("wall_thickness").forGetter(CastleStyle::wallThickness),
                    TowerShape.CODEC.fieldOf("tower_shape").forGetter(CastleStyle::towerShape),
                    Codec.INT.fieldOf("min_tower_radius").forGetter(CastleStyle::minTowerRadius),
                    Codec.INT.fieldOf("max_tower_radius").forGetter(CastleStyle::maxTowerRadius),
                    Codec.INT.fieldOf("tower_height_bonus").forGetter(CastleStyle::towerHeightBonus),
                    Codec.FLOAT.fieldOf("tower_frequency").forGetter(CastleStyle::towerFrequency),
                    Codec.BOOL.fieldOf("has_donjon").forGetter(CastleStyle::hasDonjon),
                    Codec.INT.fieldOf("donjon_min_size").forGetter(CastleStyle::donjeonMinSize),
                    Codec.INT.fieldOf("donjon_max_size").forGetter(CastleStyle::donjeonMaxSize),
                    Codec.INT.fieldOf("donjon_height_bonus").forGetter(CastleStyle::donjeonHeightBonus),
                    Codec.BOOL.fieldOf("has_inner_ward").forGetter(CastleStyle::hasInnerWard),
                    Codec.FLOAT.fieldOf("inner_ward_scale").forGetter(CastleStyle::innerWardScale),
                    Codec.BOOL.fieldOf("has_moat").forGetter(CastleStyle::hasMoat),
                    Codec.INT.fieldOf("moat_width").forGetter(CastleStyle::moatWidth),
                    Codec.INT.fieldOf("moat_depth").forGetter(CastleStyle::moatDepth),
                    Codec.BOOL.fieldOf("has_portcullis").forGetter(CastleStyle::hasPortcullis),
                    Codec.BOOL.fieldOf("has_drawbridge").forGetter(CastleStyle::hasDrawbridge),
                    MaterialPalette.CODEC.fieldOf("primary_material").forGetter(CastleStyle::primaryMaterial),
                    MaterialPalette.CODEC.fieldOf("accent_material").forGetter(CastleStyle::accentMaterial),
                    MaterialPalette.CODEC.fieldOf("floor_material").forGetter(CastleStyle::floorMaterial),
                    Identifier.CODEC.fieldOf("battlement_pool").forGetter(CastleStyle::battlementPool),
                    Identifier.CODEC.fieldOf("gatehouse_pool").forGetter(CastleStyle::gatehousePool),
                    Identifier.CODEC.fieldOf("window_pool").forGetter(CastleStyle::windowPool),
                    Identifier.CODEC.fieldOf("tower_roof_pool").forGetter(CastleStyle::towerRoofPool),
                    Identifier.CODEC.fieldOf("donjon_roof_pool").forGetter(CastleStyle::donjeonRoofPool),
                    Identifier.CODEC.optionalFieldOf("interior_pool",
                                    Identifier.parse("yourmod:castle/interiors/empty"))
                            .forGetter(CastleStyle::interiorPool),
                    Codec.FLOAT.fieldOf("ruination_level").forGetter(CastleStyle::ruinationLevel),
                    Codec.BOOL.fieldOf("add_torches").forGetter(CastleStyle::addTorches),
                    Codec.BOOL.fieldOf("add_flags").forGetter(CastleStyle::addFlags),
                    Codec.LONG.fieldOf("style_seed").forGetter(CastleStyle::styleSeed)
            ).apply(instance, CastleStyle::new)
    );

    // -------------------------------------------------------------------------
    // Convenience helpers
    // -------------------------------------------------------------------------

    /** Pick a wall height for this generation using the given random. */
    public int rollWallHeight(net.minecraft.util.RandomSource rng) {
        if (maxWallHeight <= minWallHeight) return minWallHeight;
        return minWallHeight + rng.nextInt(maxWallHeight - minWallHeight + 1);
    }

    /** Pick a tower radius for this generation. */
    public int rollTowerRadius(net.minecraft.util.RandomSource rng) {
        if (maxTowerRadius <= minTowerRadius) return minTowerRadius;
        return minTowerRadius + rng.nextInt(maxTowerRadius - minTowerRadius + 1);
    }

    /** Pick a footprint radius for this generation. */
    public int rollRadius(net.minecraft.util.RandomSource rng) {
        if (maxRadius <= minRadius) return minRadius;
        return minRadius + rng.nextInt(maxRadius - minRadius + 1);
    }

    /** Pick a donjon half-size. */
    public int rollDonjeonSize(net.minecraft.util.RandomSource rng) {
        if (donjeonMaxSize <= donjeonMinSize) return donjeonMinSize;
        return donjeonMinSize + rng.nextInt(donjeonMaxSize - donjeonMinSize + 1);
    }

    // -------------------------------------------------------------------------
    // Enum codecs
    // -------------------------------------------------------------------------

    // Note: In a real project use StringRepresentable or a simple string map.
    // These are illustrative — wire them up to your mod's codec registry.
    public static final class PlanTypeCodecHolder {
        // placeholder — replace with Codec.stringResolver(PlanType::name, PlanType::valueOf)
    }
}
