package tterrag1112.life_in_the_village.Village.Planning.Sectors;

public enum SectorRole {
    CIVIC_RING, CIVIC_TIGHT,
    SPUR_CLUSTER, RESIDENTIAL_CLUSTER, RESIDENTIAL_INFILL,
    SHORE_STRIP, RAMP_TERRACE,
    AGRICULTURAL_FRINGE, DEFENSIVE_FRINGE,
    GARDEN_RESERVATION, FESTIVAL_RESERVATION, CEMETERY_RESERVATION,
    NAMED_ANCHOR
}
