package tterrag1112.life_in_the_village.Kingdom.Provinces;

import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;

/**
 * Track D3.3 — daily snapshot of a {@link Province}'s governance
 * state. Generated by {@code ProvincialDailyTickSystem} once per
 * in-game day and appended to the province's bounded rolling
 * buffer (capacity {@code 28} = ~4 in-game weeks). Phase 5 surfaces
 * this in the audience loop UI; Phase 7 prunes older entries.
 *
 * <p>Pure data — no behaviour. Governor state, tax movements, and
 * stability deltas are recorded so the audience UI can render
 * "your governor reported X" lines without re-deriving from raw
 * tax-tick output.
 *
 * @param tickGenerated  server tick the report was created.
 * @param taxCollected   gross bronze the governor collected from
 *                       villages this day.
 * @param taxRemitted    bronze actually forwarded to the kingdom
 *                       treasury this day. Difference from
 *                       {@code taxCollected} is the governor's
 *                       skim (province treasury) plus any
 *                       withhold.
 * @param withhold       bronze the governor explicitly withheld
 *                       above the default skim. Default 0;
 *                       Phase 4's diplomacy / rebellion drivers
 *                       can lift this.
 * @param stabilityDelta net stability change applied to the
 *                       province this day (sum of recompute
 *                       contributions: governor competence,
 *                       withhold pressure, ungoverned status).
 * @param summary        short human-readable line for the
 *                       audience loop UI ("Governor remitted 80
 *                       bronze; province at peace").
 */
public record ProvincialReport(
        long tickGenerated,
        long taxCollected,
        long taxRemitted,
        long withhold,
        int stabilityDelta,
        String summary
) {

    public static final Codec<ProvincialReport> CODEC = RecordCodecBuilder.create(i -> i.group(
            Codec.LONG.fieldOf("tickGenerated").forGetter(ProvincialReport::tickGenerated),
            Codec.LONG.optionalFieldOf("taxCollected", 0L).forGetter(ProvincialReport::taxCollected),
            Codec.LONG.optionalFieldOf("taxRemitted", 0L).forGetter(ProvincialReport::taxRemitted),
            Codec.LONG.optionalFieldOf("withhold", 0L).forGetter(ProvincialReport::withhold),
            Codec.INT.optionalFieldOf("stabilityDelta", 0).forGetter(ProvincialReport::stabilityDelta),
            Codec.STRING.optionalFieldOf("summary", "").forGetter(ProvincialReport::summary)
    ).apply(i, ProvincialReport::new));

    /** Per-province rolling buffer capacity (~4 in-game weeks of daily reports). */
    public static final int BUFFER_CAPACITY = 28;
}
