// src/main/java/tterrag1112/life_in_the_village/Datagen/VillageTypeDatagen.java
package tterrag1112.life_in_the_village.Datagen;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import tterrag1112.life_in_the_village.Life_in_the_village;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;

/**
 * Generates all village type JSON files.
 *
 * <h3>Building format</h3>
 * Each entry in {@code starter_buildings} now uses {@code min_count} and
 * {@code max_count} instead of an {@code offset} array. The planner
 * ignores absolute offsets (it places buildings itself via ring/plot
 * algorithms), so the offset field was pure dead data.
 *
 * <ul>
 *   <li>{@code min_count} — minimum instances to place (default 1 if absent)</li>
 *   <li>{@code max_count} — maximum instances to place (default = min_count)</li>
 * </ul>
 *
 * A count of 1 with both fields omitted is the simplest form:
 * {@code {"type":"MARKET","structure":"market/level_1"}}
 *
 * <h3>Capital building counts</h3>
 * Capitals use higher counts for residential buildings so the planner
 * fills the city-block plots generated by CapitalLayoutPlanner.
 * The imperial capital has the densest residential population (min=10,max=14
 * houses) to fill its tighter grid.
 */
public class VillageTypeDatagen implements DataProvider {

    private final PackOutput output;

    public VillageTypeDatagen(PackOutput output) {
        this.output = output;
    }

    // =========================================================================
    // Run
    // =========================================================================

    @Override
    public CompletableFuture<?> run(CachedOutput cache) {
        List<CompletableFuture<?>> futures = new ArrayList<>();

        // Standard village types
        futures.add(saveVillageType(cache, buildDefault()));
        futures.add(saveVillageType(cache, buildFarmingVillage()));
        futures.add(saveVillageType(cache, buildMiningCamp()));
        futures.add(saveVillageType(cache, buildRiversideTown()));
        futures.add(saveVillageType(cache, buildFortressTown()));
        futures.add(saveVillageType(cache, buildTradeHub()));
        futures.add(saveVillageType(cache, buildNobleEstate()));

        // Royal capitals — one per culture
        futures.add(saveVillageType(cache, buildRoyalCapital()));
        futures.add(saveVillageType(cache, buildImperialCapital()));
        futures.add(saveVillageType(cache, buildHighlandCapital()));

        return CompletableFuture.allOf(futures.toArray(new CompletableFuture[0]));
    }

    // =========================================================================
    // ROYAL CAPITAL — default culture, PLAZA layout
    // =========================================================================
    //
    // Classic feudal monarchy. Castle north of a vast plaza. Civic ring of
    // guild hall, markets, inns. Noble quarter. Production district.
    // Military perimeter. Dense outer residential ring.
    //
    // Total unique building types: 18
    // Total instances (after count expansion): ~52

    private JsonObject buildRoyalCapital() {
        JsonObject json = new JsonObject();
        json.addProperty("type", "royal_capital");
        json.addProperty("culture", "default");
        json.add("shape_profile", shapeProfile("PLAZA", false, 3, 1.5f, true));
        json.add("capital_profile", capitalProfile(
                "ROUND",  // layout_type
                0,        // grid_spacing: 0 = auto (2*(12+2)+2*2+4 = 36 blocks)
                3,        // buildings_per_face
                9,       // building_width
                9,       // building_depth
                -4,        // face_setback
                0,        // alley_gap
                0,        // spoke_count
                true      // gate_roads
        ));

        JsonArray b = new JsonArray();
        // Power core — each is unique
        b.add(building("CASTLE",      "castle/level_1"));
        b.add(building("TOWN_HALL",   "town_hall/level_1"));
        b.add(building("CHANCELLERY", "chancellery/level_1"));
        b.add(building("TREASURY",    "treasury/level_1"));
        // Civic district
        b.add(building("GUILD_HALL",  "guild_hall/level_1"));
        b.add(buildingN("MARKET",     "market/level_1",     3));
        b.add(buildingRange("INN",        "inn/level_1",        5,10));
        b.add(building("TEMPLE",      "temple/level_1"));
        b.add(building("LIBRARY",     "library/level_1"));
        b.add(buildingRange("BELL_TOWER",  "bell_tower/level_1", 1, 2));
        // Noble quarter
        b.add(buildingRange("NOBLE_MANOR","noble_manor/level_1",10, 15));
        b.add(building("STABLE",      "stable/level_1"));
        // Production district
        b.add(buildingRange("BLACKSMITH",  "blacksmith/level_1",2,3));
        b.add(buildingRange("ARMORER",     "armorer/level_1",1,2));
        b.add(buildingRange("BAKERY",      "bakery/level_1", 2,3));
        b.add(buildingRange("APOTHECARY",  "apothecary/level_1", 1, 7));
        b.add(buildingRange("STONEMASON",  "stonemason/level_1", 2, 3));
        b.add(buildingRange("CARPENTRY", "carpentry/level_1", 2, 3));
        // Military perimeter
        b.add(building("BARRACKS",    "barracks/level_1"));
        b.add(buildingN("GUARD_TOWER","guard_tower/level_1",3));
        b.add(building("PRISON",      "prison/level_1"));
        // Residential outer ring — large count fills city-block plots
        b.add(buildingRange("HOUSE",  "house/level_1",      30, 100));
        // Storage
        b.add(buildingN("STOCKPILE",  "stockpile/level_1",  2));
        json.add("starter_buildings", b);

        JsonArray n = new JsonArray();
        // Power
        n.add(npc("KINGDOM_RULER",    "CASTLE",       "HEAD"));
        n.add(npc("VILLAGE_LEADER",   "TOWN_HALL",    "HEAD"));
        n.add(npc("CHANCELLOR",       "CHANCELLERY",  "HEAD"));
        n.add(npc("HERALD",           "TOWN_HALL",    "UNASSIGNED"));
        n.add(npc("HERALD",           "TOWN_HALL",    "UNASSIGNED"));
        n.add(npc("GUARD",            "TREASURY",     "UNASSIGNED"));
        n.add(npc("GUARD",            "TREASURY",     "UNASSIGNED"));
        // Civic
        n.add(npc("GUILDMASTER",      "GUILD_HALL",   "HEAD"));
        n.add(npc("GUILDWORKER",      "GUILD_HALL",   "UNASSIGNED"));
        n.add(npc("MERCHANT",         "MARKET",       "HEAD"));
        n.add(npc("MERCHANT",         "MARKET",       "HEAD"));
        n.add(npc("MERCHANT",         "MARKET",       "HEAD"));
        n.add(npc("INNKEEPER",        "INN",          "UNASSIGNED"));
        n.add(npc("INNKEEPER",        "INN",          "UNASSIGNED"));
        n.add(npc("PRIEST",           "TEMPLE",       "HEAD"));
        n.add(npc("SCHOLAR",          "LIBRARY",      "HEAD"));
        n.add(npc("SCHOLAR",          "LIBRARY",      "UNASSIGNED"));
        // Production
        n.add(npc("BLACKSMITH",       "BLACKSMITH",   "HEAD"));
        n.add(npc("BUILDER",          "TOWN_HALL",    "HEAD"));
        // Military
        n.add(npc("GUARD",            "BARRACKS",     "HEAD"));
        n.add(npc("GUARD",            "BARRACKS",     "UNASSIGNED"));
        n.add(npc("GUARD",            "BARRACKS",     "UNASSIGNED"));
        n.add(npc("GUARD",            "GUARD_TOWER",  "HEAD"));
        n.add(npc("GUARD",            "GUARD_TOWER",  "HEAD"));
        n.add(npc("GUARD",            "GUARD_TOWER",  "HEAD"));
        // Storage + residents (NPCs cycle across all HOUSE instances)
        n.add(npc("STOCKPILE_KEEPER", "STOCKPILE",    "HEAD"));
        n.add(npc("STOCKPILE_KEEPER", "STOCKPILE",    "HEAD"));
        n.add(npc("NONE",             "HOUSE",        "HEAD"));
        n.add(npc("NONE",             "HOUSE",        "HEAD"));
        n.add(npc("NONE",             "HOUSE",        "HEAD"));
        n.add(npc("NONE",             "HOUSE",        "HEAD"));
        n.add(npc("NONE",             "HOUSE",        "HEAD"));
        n.add(npc("NONE",             "HOUSE",        "HEAD"));
        n.add(npc("NONE",             "HOUSE",        "HEAD"));
        n.add(npc("NONE",             "HOUSE",        "HEAD"));
        json.add("starter_npcs", n);

        JsonArray i = new JsonArray();
        i.add(item("TREASURY",   "life_in_the_village:denier_or",  256));
        i.add(item("CASTLE",     "life_in_the_village:denier_or",  128));
        i.add(item("STOCKPILE",  "minecraft:cobblestone",          512));
        i.add(item("STOCKPILE",  "minecraft:stone_bricks",         256));
        i.add(item("STOCKPILE",  "minecraft:iron_ingot",            64));
        i.add(item("STOCKPILE",  "minecraft:gold_ingot",            32));
        i.add(item("STOCKPILE",  "minecraft:oak_log",              128));
        i.add(item("STOCKPILE",  "minecraft:bread",                 64));
        i.add(item("BARRACKS",   "minecraft:iron_sword",             8));
        i.add(item("BARRACKS",   "minecraft:iron_chestplate",        4));
        i.add(item("BARRACKS",   "minecraft:iron_helmet",            4));
        i.add(item("LIBRARY",    "minecraft:book",                  16));
        json.add("starter_items", i);
        return json;
    }

    // =========================================================================
    // IMPERIAL CAPITAL — imperial culture, COURTYARD layout + grid streets
    // =========================================================================
    //
    // Roman/Byzantine-inspired empire. Palace inner ward, dual senate
    // buildings, two libraries, two temples. Dense residential population
    // filling city-block grid (10–14 houses). Legionary barracks.
    // The COURTYARD shape + grid overlay produces a planned, formal look.
    //
    // Residential count range (10–14) drives the grid density — CapitalLayout
    // Planner expands this to a random number each spawn, so no two imperial
    // capitals look identical.
    //
    // Total unique building types: 20
    // Total instances (min expansion): ~58, max: ~62

    private JsonObject buildImperialCapital() {
        JsonObject json = new JsonObject();
        json.addProperty("type", "imperial_capital");
        json.addProperty("culture", "imperial");
        json.add("shape_profile", shapeProfile("COURTYARD", false, 3, 1.4f, true));
        json.add("capital_profile", capitalProfile(
                "ROUND",  // layout_type
                0,        // grid_spacing: 0 = auto (2*(12+2)+2*2+4 = 36 blocks)
                2,        // buildings_per_face
                12,       // building_width
                10,       // building_depth
                2,        // face_setback
                2,        // alley_gap
                6,        // spoke_count
                true      // gate_roads
        ));

        JsonArray b = new JsonArray();
        // Palace complex (inner ward)
        b.add(building("CASTLE",      "castle/level_1"));
        b.add(buildingN("CHANCELLERY","chancellery/level_1", 2)); // dual senate
        b.add(building("TREASURY",    "treasury/level_1"));
        // Forum / civic district
        b.add(buildingN("MARKET",     "market/level_1",      2));
        b.add(building("GUILD_HALL",  "guild_hall/level_1"));
        b.add(buildingRange("INN",         "inn/level_1", 2, 10));
        b.add(building("STABLE",      "stable/level_1"));
        // Cultural district — two of each for symmetry
        b.add(buildingN("LIBRARY",    "library/level_1",     2));
        b.add(buildingN("TEMPLE",     "temple/level_1",      2));
        b.add(buildingN("APOTHECARY",  "apothecary/level_1", 2));
        // Noble villas
        b.add(buildingRange("NOBLE_MANOR","noble_manor/level_1", 3, 7));
        // Workshops
        b.add(building("BLACKSMITH",  "blacksmith/level_1"));
        b.add(building("ARMORER",     "armorer/level_1"));
        b.add(building("STONEMASON",  "stonemason/level_1"));
        b.add(building("BAKERY",      "bakery/level_1"));
        b.add(building("ATELIER",     "atelier/level_1"));
        // Military
        b.add(building("BARRACKS",    "barracks/level_1"));
        b.add(buildingN("GUARD_TOWER","guard_tower/level_1", 2));
        b.add(building("WATCHTOWER",  "watchtower/level_1"));
        b.add(building("PRISON",      "prison/level_1"));
        // Residential — dense range fills the grid-block plots
        b.add(buildingRange("HOUSE",  "house/level_1",       15, 30));
        // Storage
        b.add(buildingN("STOCKPILE",  "stockpile/level_1",   2));
        json.add("starter_buildings", b);

        JsonArray n = new JsonArray();
        n.add(npc("KINGDOM_RULER",    "CASTLE",       "HEAD"));
        n.add(npc("VILLAGE_LEADER",   "TOWN_HALL",    "HEAD"));
        n.add(npc("CHANCELLOR",       "CHANCELLERY",  "HEAD"));
        n.add(npc("CHANCELLOR",       "CHANCELLERY",  "UNASSIGNED"));
        n.add(npc("HERALD",           "TOWN_HALL",    "UNASSIGNED"));
        n.add(npc("GUARD",            "TREASURY",     "UNASSIGNED"));
        n.add(npc("GUARD",            "TREASURY",     "UNASSIGNED"));
        n.add(npc("MERCHANT",         "MARKET",       "HEAD"));
        n.add(npc("MERCHANT",         "MARKET",       "HEAD"));
        n.add(npc("GUILDMASTER",      "GUILD_HALL",   "HEAD"));
        n.add(npc("INNKEEPER",        "INN",          "UNASSIGNED"));
        n.add(npc("SCHOLAR",          "LIBRARY",      "HEAD"));
        n.add(npc("SCHOLAR",          "LIBRARY",      "HEAD"));
        n.add(npc("SCHOLAR",          "LIBRARY",      "UNASSIGNED"));
        n.add(npc("PRIEST",           "TEMPLE",       "HEAD"));
        n.add(npc("PRIEST",           "TEMPLE",       "HEAD"));
        n.add(npc("BLACKSMITH",       "BLACKSMITH",   "HEAD"));
        n.add(npc("BUILDER",          "TOWN_HALL",    "HEAD"));
        n.add(npc("GUARD",            "BARRACKS",     "HEAD"));
        n.add(npc("GUARD",            "BARRACKS",     "UNASSIGNED"));
        n.add(npc("GUARD",            "BARRACKS",     "UNASSIGNED"));
        n.add(npc("GUARD",            "GUARD_TOWER",  "HEAD"));
        n.add(npc("GUARD",            "GUARD_TOWER",  "HEAD"));
        n.add(npc("STOCKPILE_KEEPER", "STOCKPILE",    "HEAD"));
        n.add(npc("STOCKPILE_KEEPER", "STOCKPILE",    "HEAD"));
        // Residents cycling across all house instances
        for (int k = 0; k < 10; k++) n.add(npc("NONE", "HOUSE", "HEAD"));
        json.add("starter_npcs", n);

        JsonArray i = new JsonArray();
        i.add(item("TREASURY",   "life_in_the_village:denier_or",  320));
        i.add(item("CASTLE",     "life_in_the_village:denier_or",  192));
        i.add(item("STOCKPILE",  "minecraft:stone_bricks",         512));
        i.add(item("STOCKPILE",  "minecraft:cobblestone",          256));
        i.add(item("STOCKPILE",  "minecraft:iron_ingot",            96));
        i.add(item("STOCKPILE",  "minecraft:gold_ingot",            48));
        i.add(item("STOCKPILE",  "minecraft:bread",                 64));
        i.add(item("BARRACKS",   "minecraft:iron_sword",            12));
        i.add(item("BARRACKS",   "minecraft:iron_chestplate",        6));
        i.add(item("LIBRARY",    "minecraft:book",                  32));
        i.add(item("LIBRARY",    "minecraft:writable_book",          8));
        json.add("starter_items", i);
        return json;
    }

    // =========================================================================
    // HIGHLAND CAPITAL — highland culture, HILLTOP layout
    // =========================================================================
    //
    // Celtic fortress-city on a hill. Castle at the peak. Military-heavy:
    // 2 barracks, 4 guard towers, 2 watchtowers. No farm plots.
    // Moderate residential count (6–8 houses).
    //
    // Total unique building types: 18
    // Total instances (min expansion): ~44, max: ~46

    private JsonObject buildHighlandCapital() {
        JsonObject json = new JsonObject();
        json.addProperty("type", "highland_capital");
        json.addProperty("culture", "highland");
        json.add("shape_profile", shapeProfile("HILLTOP", false, 2, 1.2f, true));

        JsonArray b = new JsonArray();
        // Fortress peak
        b.add(building("CASTLE",      "castle/level_1"));
        b.add(building("TOWN_HALL",   "town_hall/level_1"));
        b.add(building("CHANCELLERY", "chancellery/level_1"));
        b.add(building("TREASURY",    "treasury/level_1"));
        // Heavy military
        b.add(buildingN("BARRACKS",   "barracks/level_1",    2));
        b.add(buildingN("GUARD_TOWER","guard_tower/level_1", 4));
        b.add(buildingN("WATCHTOWER", "watchtower/level_1",  2));
        b.add(building("PRISON",      "prison/level_1"));
        // Smithing quarter
        b.add(building("BLACKSMITH",  "blacksmith/level_1"));
        b.add(building("ARMORER",     "armorer/level_1"));
        b.add(building("STONEMASON",  "stonemason/level_1"));
        b.add(building("WOODCUTTER",  "woodcutter/level_1"));
        // Civic
        b.add(buildingN("MARKET",     "market/level_1",      2));
        b.add(building("INN",         "inn/level_1"));
        b.add(building("TEMPLE",      "temple/level_1"));
        b.add(building("GUILD_HALL",  "guild_hall/level_1"));
        b.add(building("STABLE",      "stable/level_1"));
        b.add(building("NOBLE_MANOR", "noble_manor/level_1"));
        // Residential
        b.add(buildingRange("HOUSE",  "house/level_1",        6, 8));
        // Storage
        b.add(buildingN("STOCKPILE",  "stockpile/level_1",    2));
        json.add("starter_buildings", b);

        JsonArray n = new JsonArray();
        n.add(npc("KINGDOM_RULER",    "CASTLE",       "HEAD"));
        n.add(npc("VILLAGE_LEADER",   "TOWN_HALL",    "HEAD"));
        n.add(npc("CHANCELLOR",       "CHANCELLERY",  "HEAD"));
        n.add(npc("HERALD",           "TOWN_HALL",    "UNASSIGNED"));
        n.add(npc("GUARD",            "TREASURY",     "UNASSIGNED"));
        n.add(npc("GUARD",            "TREASURY",     "UNASSIGNED"));
        n.add(npc("GUARD",            "BARRACKS",     "HEAD"));
        n.add(npc("GUARD",            "BARRACKS",     "HEAD"));
        n.add(npc("GUARD",            "BARRACKS",     "UNASSIGNED"));
        n.add(npc("GUARD",            "BARRACKS",     "UNASSIGNED"));
        n.add(npc("GUARD",            "BARRACKS",     "UNASSIGNED"));
        n.add(npc("GUARD",            "GUARD_TOWER",  "HEAD"));
        n.add(npc("GUARD",            "GUARD_TOWER",  "HEAD"));
        n.add(npc("GUARD",            "GUARD_TOWER",  "HEAD"));
        n.add(npc("GUARD",            "GUARD_TOWER",  "HEAD"));
        n.add(npc("BLACKSMITH",       "BLACKSMITH",   "HEAD"));
        n.add(npc("BUILDER",          "TOWN_HALL",    "HEAD"));
        n.add(npc("MERCHANT",         "MARKET",       "HEAD"));
        n.add(npc("MERCHANT",         "MARKET",       "HEAD"));
        n.add(npc("GUILDMASTER",      "GUILD_HALL",   "HEAD"));
        n.add(npc("INNKEEPER",        "INN",          "UNASSIGNED"));
        n.add(npc("PRIEST",           "TEMPLE",       "HEAD"));
        n.add(npc("STOCKPILE_KEEPER", "STOCKPILE",    "HEAD"));
        n.add(npc("STOCKPILE_KEEPER", "STOCKPILE",    "HEAD"));
        for (int k = 0; k < 6; k++) n.add(npc("NONE", "HOUSE", "HEAD"));
        json.add("starter_npcs", n);

        JsonArray i = new JsonArray();
        i.add(item("TREASURY",   "life_in_the_village:denier_or",  200));
        i.add(item("CASTLE",     "life_in_the_village:denier_or",  160));
        i.add(item("STOCKPILE",  "minecraft:cobblestone",          512));
        i.add(item("STOCKPILE",  "minecraft:iron_ingot",           128));
        i.add(item("STOCKPILE",  "minecraft:bread",                 96));
        i.add(item("BARRACKS",   "minecraft:iron_sword",            16));
        i.add(item("BARRACKS",   "minecraft:iron_chestplate",        8));
        i.add(item("BARRACKS",   "minecraft:iron_helmet",            8));
        i.add(item("BARRACKS",   "minecraft:bow",                    8));
        json.add("starter_items", i);
        return json;
    }

    // =========================================================================
    // Standard village types
    // =========================================================================

    private JsonObject buildDefault() {
        JsonObject json = new JsonObject();
        json.addProperty("type", "default");
        json.addProperty("culture", "default");
        json.add("shape_profile", shapeProfile("RADIAL", false, 2, 1.0f, false));

        JsonArray b = new JsonArray();
        b.add(building("TOWN_HALL",   "town_hall/level_1"));
        b.add(building("STOCKPILE",   "stockpile/level_1"));
        b.add(building("FARMHOUSE",   "farmhouse/level_1"));
        b.add(buildingN("HOUSE",      "house/level_1",       3));
        b.add(building("GUILD_HALL",  "guild_hall/level_1"));
        b.add(building("GUARD_TOWER", "guard_tower/level_1"));
        b.add(building("MINE",        "mine/level_1"));
        b.add(building("BLACKSMITH",  "blacksmith/level_1"));
        b.add(building("INN",         "inn/level_1"));
        json.add("starter_buildings", b);

        JsonArray n = new JsonArray();
        n.add(npc("BUILDER",          "TOWN_HALL",   "HEAD"));
        n.add(npc("VILLAGE_LEADER",   "TOWN_HALL",   "HEAD"));
        n.add(npc("FARMER",           "FARMHOUSE",   "HEAD"));
        n.add(npc("GUARD",            "TOWN_HALL",   "UNASSIGNED"));
        n.add(npc("STOCKPILE_KEEPER", "STOCKPILE",   "HEAD"));
        n.add(npc("NONE",             "HOUSE",       "HEAD"));
        n.add(npc("GUILDWORKER",      "GUILD_HALL",  "UNASSIGNED"));
        n.add(npc("GUILDMASTER",      "GUILD_HALL",  "HEAD"));
        n.add(npc("GUARD",            "GUARD_TOWER", "HEAD"));
        n.add(npc("MINER",            "MINE",        "HEAD"));
        n.add(npc("BLACKSMITH",       "BLACKSMITH",  "HEAD"));
        n.add(npc("INNKEEPER",        "INN",         "UNASSIGNED"));
        json.add("starter_npcs", n);

        JsonArray items = new JsonArray();
        items.add(item("STOCKPILE", "minecraft:wheat_seeds",  64));
        items.add(item("STOCKPILE", "minecraft:oak_log",      64));
        items.add(item("STOCKPILE", "minecraft:cobblestone",  128));
        items.add(item("STOCKPILE", "minecraft:iron_ingot",   16));
        items.add(item("TOWN_HALL", "life_in_the_village:denier_or", 16));
        json.add("starter_items", items);
        return json;
    }

    private JsonObject buildFarmingVillage() {
        JsonObject json = new JsonObject();
        json.addProperty("type", "farming_village");
        json.addProperty("culture", "default");
        json.add("shape_profile", shapeProfile("LINEAR", true, 1, 1.1f, false));

        JsonArray b = new JsonArray();
        b.add(building("TOWN_HALL",  "town_hall/level_1"));
        b.add(building("STOCKPILE",  "stockpile/level_1"));
        b.add(buildingN("FARMHOUSE", "farmhouse/level_1", 2));
        b.add(building("HOUSE",      "house/level_1"));
        b.add(building("MARKET",     "market/level_1"));
        json.add("starter_buildings", b);

        JsonArray n = new JsonArray();
        n.add(npc("BUILDER",          "TOWN_HALL",  "HEAD"));
        n.add(npc("FARMER",           "FARMHOUSE",  "HEAD"));
        n.add(npc("FARMER",           "FARMHOUSE",  "HEAD"));
        n.add(npc("STOCKPILE_KEEPER", "STOCKPILE",  "HEAD"));
        n.add(npc("NONE",             "HOUSE",      "HEAD"));
        n.add(npc("MERCHANT",         "MARKET",     "HEAD"));
        json.add("starter_npcs", n);

        JsonArray items = new JsonArray();
        items.add(item("STOCKPILE", "minecraft:wheat_seeds", 128));
        items.add(item("STOCKPILE", "minecraft:carrot",       64));
        items.add(item("STOCKPILE", "minecraft:potato",       64));
        items.add(item("STOCKPILE", "minecraft:oak_log",      64));
        items.add(item("STOCKPILE", "minecraft:cobblestone",  128));
        json.add("starter_items", items);
        return json;
    }

    private JsonObject buildMiningCamp() {
        JsonObject json = new JsonObject();
        json.addProperty("type", "mining_camp");
        json.addProperty("culture", "default");
        json.add("shape_profile", shapeProfile("CLUSTERED", false, 1, 0.7f, false));

        JsonArray b = new JsonArray();
        b.add(building("TOWN_HALL",  "town_hall/level_1"));
        b.add(building("STOCKPILE",  "stockpile/level_1"));
        b.add(buildingN("MINE",      "mine/level_1",       2));
        b.add(building("BLACKSMITH", "blacksmith/level_1"));
        b.add(buildingN("HOUSE",     "house/level_1",      2));
        b.add(building("INN",        "inn/level_1"));
        json.add("starter_buildings", b);

        JsonArray n = new JsonArray();
        n.add(npc("BUILDER",          "TOWN_HALL",  "HEAD"));
        n.add(npc("VILLAGE_LEADER",   "TOWN_HALL",  "HEAD"));
        n.add(npc("MINER",            "MINE",       "HEAD"));
        n.add(npc("MINER",            "MINE",       "HEAD"));
        n.add(npc("STOCKPILE_KEEPER", "STOCKPILE",  "HEAD"));
        n.add(npc("BLACKSMITH",       "BLACKSMITH", "HEAD"));
        n.add(npc("NONE",             "HOUSE",      "HEAD"));
        n.add(npc("NONE",             "HOUSE",      "HEAD"));
        n.add(npc("INNKEEPER",        "INN",        "UNASSIGNED"));
        json.add("starter_npcs", n);

        JsonArray items = new JsonArray();
        items.add(item("STOCKPILE", "minecraft:cobblestone", 256));
        items.add(item("STOCKPILE", "minecraft:oak_log",      64));
        items.add(item("STOCKPILE", "minecraft:iron_ingot",   32));
        items.add(item("STOCKPILE", "minecraft:torch",        64));
        items.add(item("STOCKPILE", "minecraft:bread",        32));
        json.add("starter_items", items);
        return json;
    }

    private JsonObject buildRiversideTown() {
        JsonObject json = new JsonObject();
        json.addProperty("type", "riverside_town");
        json.addProperty("culture", "default");
        json.add("shape_profile", shapeProfile("RIVERINE", true, 2, 0.9f, false));

        JsonArray b = new JsonArray();
        b.add(building("TOWN_HALL",  "town_hall/level_1"));
        b.add(building("STOCKPILE",  "stockpile/level_1"));
        b.add(building("MARKET",     "market/level_1"));
        b.add(building("INN",        "inn/level_1"));
        b.add(building("FARMHOUSE",  "farmhouse/level_1"));
        b.add(building("CARPENTRY",  "carpentry/level_1"));
        b.add(buildingN("HOUSE",     "house/level_1", 3));
        json.add("starter_buildings", b);

        JsonArray n = new JsonArray();
        n.add(npc("BUILDER",          "TOWN_HALL",  "HEAD"));
        n.add(npc("VILLAGE_LEADER",   "TOWN_HALL",  "HEAD"));
        n.add(npc("STOCKPILE_KEEPER", "STOCKPILE",  "HEAD"));
        n.add(npc("MERCHANT",         "MARKET",     "HEAD"));
        n.add(npc("INNKEEPER",        "INN",        "UNASSIGNED"));
        n.add(npc("FARMER",           "FARMHOUSE",  "HEAD"));
        n.add(npc("CARPENTER",        "CARPENTRY",  "HEAD"));
        n.add(npc("NONE",             "HOUSE",      "HEAD"));
        n.add(npc("NONE",             "HOUSE",      "HEAD"));
        n.add(npc("NONE",             "HOUSE",      "HEAD"));
        json.add("starter_npcs", n);

        JsonArray items = new JsonArray();
        items.add(item("STOCKPILE", "minecraft:wheat_seeds",  64));
        items.add(item("STOCKPILE", "minecraft:oak_log",     128));
        items.add(item("STOCKPILE", "minecraft:cobblestone",  64));
        items.add(item("STOCKPILE", "minecraft:bread",        32));
        items.add(item("TOWN_HALL", "life_in_the_village:denier_or", 24));
        json.add("starter_items", items);
        return json;
    }

    private JsonObject buildFortressTown() {
        JsonObject json = new JsonObject();
        json.addProperty("type", "fortress_town");
        json.addProperty("culture", "default");
        json.add("shape_profile", shapeProfile("HILLTOP", false, 2, 0.6f, true));

        JsonArray b = new JsonArray();
        b.add(building("TOWN_HALL",   "town_hall/level_1"));
        b.add(building("STOCKPILE",   "stockpile/level_1"));
        b.add(buildingN("GUARD_TOWER","guard_tower/level_1", 2));
        b.add(building("BLACKSMITH",  "blacksmith/level_1"));
        b.add(building("INN",         "inn/level_1"));
        b.add(buildingN("HOUSE",      "house/level_1",       3));
        json.add("starter_buildings", b);

        JsonArray n = new JsonArray();
        n.add(npc("BUILDER",          "TOWN_HALL",   "HEAD"));
        n.add(npc("VILLAGE_LEADER",   "TOWN_HALL",   "HEAD"));
        n.add(npc("GUARD",            "GUARD_TOWER", "HEAD"));
        n.add(npc("GUARD",            "GUARD_TOWER", "HEAD"));
        n.add(npc("GUARD",            "TOWN_HALL",   "UNASSIGNED"));
        n.add(npc("STOCKPILE_KEEPER", "STOCKPILE",   "HEAD"));
        n.add(npc("BLACKSMITH",       "BLACKSMITH",  "HEAD"));
        n.add(npc("INNKEEPER",        "INN",         "UNASSIGNED"));
        n.add(npc("NONE",             "HOUSE",       "HEAD"));
        n.add(npc("NONE",             "HOUSE",       "HEAD"));
        n.add(npc("NONE",             "HOUSE",       "HEAD"));
        json.add("starter_npcs", n);

        JsonArray items = new JsonArray();
        items.add(item("STOCKPILE", "minecraft:cobblestone", 256));
        items.add(item("STOCKPILE", "minecraft:iron_ingot",   64));
        items.add(item("STOCKPILE", "minecraft:iron_sword",    4));
        items.add(item("STOCKPILE", "minecraft:iron_helmet",   4));
        items.add(item("STOCKPILE", "minecraft:bread",        48));
        items.add(item("TOWN_HALL", "life_in_the_village:denier_or", 32));
        json.add("starter_items", items);
        return json;
    }

    private JsonObject buildTradeHub() {
        JsonObject json = new JsonObject();
        json.addProperty("type", "trade_hub");
        json.addProperty("culture", "default");
        json.add("shape_profile", shapeProfile("PLAZA", false, 2, 1.2f, false));

        JsonArray b = new JsonArray();
        b.add(building("TOWN_HALL",  "town_hall/level_1"));
        b.add(building("STOCKPILE",  "stockpile/level_1"));
        b.add(buildingN("MARKET",    "market/level_1",    2));
        b.add(building("INN",        "inn/level_1"));
        b.add(building("GUILD_HALL", "guild_hall/level_1"));
        b.add(building("BLACKSMITH", "blacksmith/level_1"));
        b.add(building("CARPENTRY",  "carpentry/level_1"));
        b.add(building("FARMHOUSE",  "farmhouse/level_1"));
        b.add(buildingN("HOUSE",     "house/level_1",     3));
        json.add("starter_buildings", b);

        JsonArray n = new JsonArray();
        n.add(npc("BUILDER",          "TOWN_HALL",  "HEAD"));
        n.add(npc("VILLAGE_LEADER",   "TOWN_HALL",  "HEAD"));
        n.add(npc("STOCKPILE_KEEPER", "STOCKPILE",  "HEAD"));
        n.add(npc("MERCHANT",         "MARKET",     "HEAD"));
        n.add(npc("MERCHANT",         "MARKET",     "HEAD"));
        n.add(npc("INNKEEPER",        "INN",        "UNASSIGNED"));
        n.add(npc("GUILDMASTER",      "GUILD_HALL", "HEAD"));
        n.add(npc("GUILDWORKER",      "GUILD_HALL", "UNASSIGNED"));
        n.add(npc("BLACKSMITH",       "BLACKSMITH", "HEAD"));
        n.add(npc("CARPENTER",        "CARPENTRY",  "HEAD"));
        n.add(npc("FARMER",           "FARMHOUSE",  "HEAD"));
        n.add(npc("NONE",             "HOUSE",      "HEAD"));
        n.add(npc("NONE",             "HOUSE",      "HEAD"));
        n.add(npc("NONE",             "HOUSE",      "HEAD"));
        json.add("starter_npcs", n);

        JsonArray items = new JsonArray();
        items.add(item("STOCKPILE", "minecraft:wheat_seeds",  64));
        items.add(item("STOCKPILE", "minecraft:oak_log",      64));
        items.add(item("STOCKPILE", "minecraft:cobblestone",  128));
        items.add(item("STOCKPILE", "minecraft:iron_ingot",   32));
        items.add(item("STOCKPILE", "minecraft:gold_ingot",    8));
        items.add(item("TOWN_HALL", "life_in_the_village:denier_or", 48));
        json.add("starter_items", items);
        return json;
    }

    private JsonObject buildNobleEstate() {
        JsonObject json = new JsonObject();
        json.addProperty("type", "noble_estate");
        json.addProperty("culture", "default");
        json.add("shape_profile", shapeProfile("COURTYARD", false, 2, 0.8f, true));

        JsonArray b = new JsonArray();
        b.add(building("TOWN_HALL",   "town_hall/level_1"));
        b.add(building("STOCKPILE",   "stockpile/level_1"));
        b.add(building("BLACKSMITH",  "blacksmith/level_1"));
        b.add(building("CARPENTRY",   "carpentry/level_1"));
        b.add(building("INN",         "inn/level_1"));
        b.add(building("GUARD_TOWER", "guard_tower/level_1"));
        b.add(building("FARMHOUSE",   "farmhouse/level_1"));
        b.add(buildingN("HOUSE",      "house/level_1", 3));
        json.add("starter_buildings", b);

        JsonArray n = new JsonArray();
        n.add(npc("BUILDER",          "TOWN_HALL",   "HEAD"));
        n.add(npc("VILLAGE_LEADER",   "TOWN_HALL",   "HEAD"));
        n.add(npc("STOCKPILE_KEEPER", "STOCKPILE",   "HEAD"));
        n.add(npc("BLACKSMITH",       "BLACKSMITH",  "HEAD"));
        n.add(npc("CARPENTER",        "CARPENTRY",   "HEAD"));
        n.add(npc("INNKEEPER",        "INN",         "UNASSIGNED"));
        n.add(npc("GUARD",            "GUARD_TOWER", "HEAD"));
        n.add(npc("GUARD",            "TOWN_HALL",   "UNASSIGNED"));
        n.add(npc("FARMER",           "FARMHOUSE",   "HEAD"));
        n.add(npc("NONE",             "HOUSE",       "HEAD"));
        n.add(npc("NONE",             "HOUSE",       "HEAD"));
        n.add(npc("NONE",             "HOUSE",       "HEAD"));
        json.add("starter_npcs", n);

        JsonArray items = new JsonArray();
        items.add(item("STOCKPILE", "minecraft:wheat_seeds",  64));
        items.add(item("STOCKPILE", "minecraft:oak_log",     128));
        items.add(item("STOCKPILE", "minecraft:cobblestone",  128));
        items.add(item("STOCKPILE", "minecraft:iron_ingot",   48));
        items.add(item("STOCKPILE", "minecraft:bread",        32));
        items.add(item("TOWN_HALL", "life_in_the_village:denier_or", 40));
        json.add("starter_items", items);
        return json;
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    /**
     * Single instance of a building type. The registry defaults min_count
     * and max_count to 1 when these fields are absent, so no fields are
     * needed for the common case.
     */
    private JsonObject building(String type, String structure) {
        JsonObject obj = new JsonObject();
        obj.addProperty("type", type);
        obj.addProperty("structure", structure);
        return obj;
    }

    /**
     * Exact count — always places exactly {@code count} instances.
     * Equivalent to min_count == max_count == count.
     */
    private JsonObject buildingN(String type, String structure, int count) {
        JsonObject obj = new JsonObject();
        obj.addProperty("type", type);
        obj.addProperty("structure", structure);
        obj.addProperty("min_count", count);
        obj.addProperty("max_count", count);
        return obj;
    }

    /**
     * Count range — the planner picks a random number in [minCount, maxCount]
     * at spawn time. Useful for residential buildings so no two capitals
     * look identical.
     */
    private JsonObject buildingRange(String type, String structure,
                                     int minCount, int maxCount) {
        JsonObject obj = new JsonObject();
        obj.addProperty("type", type);
        obj.addProperty("structure", structure);
        obj.addProperty("min_count", minCount);
        obj.addProperty("max_count", maxCount);
        return obj;
    }

    private JsonObject npc(String profession, String buildingType,
                           String familyRole) {
        JsonObject obj = new JsonObject();
        obj.addProperty("profession", profession);
        obj.addProperty("building_type", buildingType);
        obj.addProperty("family_role", familyRole);
        return obj;
    }

    private JsonObject item(String buildingType, String itemId, int count) {
        JsonObject obj = new JsonObject();
        obj.addProperty("building_type", buildingType);
        obj.addProperty("item", itemId);
        obj.addProperty("count", count);
        return obj;
    }

    /**
     * Creates a {@code shape_profile} JSON object.
     *
     * @param shapeType      RADIAL | LINEAR | CLUSTERED | RIVERINE |
     *                       HILLTOP | PLAZA | COURTYARD
     * @param forcedAxis     for LINEAR — align to terrain's flattest axis
     * @param maxRings       maximum ring count
     * @param streetDensity  building spacing multiplier
     * @param walledByDefault always place a perimeter wall
     */
    private JsonObject shapeProfile(String shapeType, boolean forcedAxis,
                                    int maxRings, float streetDensity,
                                    boolean walledByDefault) {
        JsonObject sp = new JsonObject();
        sp.addProperty("shape_type",        shapeType);
        sp.addProperty("forced_axis",       forcedAxis);
        sp.addProperty("max_rings",         maxRings);
        sp.addProperty("street_density",    streetDensity);
        sp.addProperty("walled_by_default", walledByDefault);
        return sp;
    }

    private CompletableFuture<?> saveVillageType(CachedOutput cache,
                                                 JsonObject json) {
        String type = json.get("type").getAsString();
        Path path   = output.getOutputFolder()
                .resolve("data/" + Life_in_the_village.MODID
                        + "/village_types/" + type + ".json");
        return DataProvider.saveStable(cache,
                new GsonBuilder().setPrettyPrinting()
                        .create().toJsonTree(json),
                path);
    }
    private JsonObject capitalProfile(String layoutType, int gridSpacing,
                                      int buildingsPerFace,
                                      int buildingWidth, int buildingDepth,
                                      int faceSetback, int alleyGap,
                                      int spokeCount, boolean gateRoads) {
        JsonObject cp = new JsonObject();
        cp.addProperty("layout_type",        layoutType);
        cp.addProperty("grid_spacing",       gridSpacing);
        cp.addProperty("buildings_per_face", buildingsPerFace);
        cp.addProperty("building_width",     buildingWidth);
        cp.addProperty("building_depth",     buildingDepth);
        cp.addProperty("face_setback",       faceSetback);
        cp.addProperty("alley_gap",          alleyGap);
        cp.addProperty("spoke_count",        spokeCount);
        cp.addProperty("gate_roads",         gateRoads);
        return cp;
    }

    @Override
    public String getName() {
        return "Life in the Village Village Types";
    }
}